- name: Launch database
  docker_container:
    name: database
    image: paulinemaitre/devops:database
    state: started
    networks:
      - name: app-network
    env:
      POSTGRES_PASSWORD=pwd
      POSTGRES_USER=usr
      POSTGRES_DB=db
    pull: true
    volumes:
      my_db_volume:
        driver: local
