language: java

script:
- mvn clean verify --file ./simple-api/pom.xml
- docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
- docker build -t paulinemaitre/devops:database database
- docker build -t paulinemaitre/devops:simple-api simple-api
- docker build -t paulinemaitre/devops:httpd httpd
- docker push paulinemaitre/devops:database
- docker push paulinemaitre/devops:simple-api
- docker push paulinemaitre/devops:httpd

cache:
  directories:
    - $HOME/.m2
