language: java

script:
- cd ./simple-api
- mvn clean verify
- docker login $DOCKER_LOGIN $DOCKER_PASSWORD
#- docker push correction-tp1-master/database
#- docker push correction-tp1-master/database
#- docker push correction-tp1-master/database
# build
# publication des images

cache :
directories :
  - $HOME/.m2
services :
  - docker
