- name: Launch front
  docker_container:
    name: front
    image: paulinemaitre/devops:front
    state: started
    ports:
      - 80:80
    networks:
      - name: app-network
        #links:
          #- database

