- name: Launch app
  docker_container:
    name: backend
    image: paulinemaitre/devops:simple-api
    state: present
    networks:
      - name: app-network
    env:
      SPRING_DATASOURCE_USERNAME=usr
      SPRING_DATASOURCE_PASSWORD=pwd
      SPRING_DATASOURCE_URL=db

