- name: Launch app
  docker_container:
    name: backend
    image: paulinemaitre/devops:simple-api
    state: started
    networks:
      - name: app-network
    env:
      username=usr
      password=pwd
    pull: yes

