- name: Launch proxy
  docker_container:
    name: reverse_proxy
    image: paulinemaitre/devops:httpd
    state: started
    ports:
      - 8080:8080
      #- 80:80
    networks:
      - name: app-network
