- name: Launch proxy
  docker_container:
    name: reverse_proxy
    image: paulinemaitre/devops:httpd
    ports:
      - 80:80
    networks:
      - name: app-network
    pull: yes
    recreate: yes
